question_data = [
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science: Computers",
            "question": "The name of the programming language AWK is abbreviated from the names of the developers &ndash; Aho, Weinberger, and Kernighan.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "multiple",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "What does the term GPU stand for?",
            "correct_answer": "Graphics Processing Unit",
            "incorrect_answers": [
                "Gaming Processor Unit",
                "Graphite Producing Unit",
                "Graphical Proprietary Unit",
            ],
        },
        {
            "type": "multiple",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "Originally used in PCM adapters, what frequency is the standard for sampling audio in the Compact Disc Digital Audio format?",
            "correct_answer": "44.1 kHz",
            "incorrect_answers": ["32.0 kHz", "1.5 MHz", "20.5 kHz"],
        },
        {
            "type": "multiple",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "What is known as &quot;the brain&quot; of the Computer?",
            "correct_answer": "Central Processing Unit",
            "incorrect_answers": [
                "Motherboard",
                "Graphics Processing Unit",
                "Keyboard",
            ],
        },
        {
            "type": "multiple",
            "difficulty": "easy",
            "category": "Science: Computers",
            "question": "In the programming language Java, which of these keywords would you put on a variable to make sure it doesn&#039;t get modified?",
            "correct_answer": "Final",
            "incorrect_answers": ["Static", "Private", "Public"],
        },
        {
            "type": "multiple",
            "difficulty": "hard",
            "category": "Science: Computers",
            "question": "Which of these was the name of a bug found in April 2014 in the publicly available OpenSSL cryptography library?",
            "correct_answer": "Heartbleed",
            "incorrect_answers": ["Shellshock", "Corrupted Blood", "Shellscript"],
        },
        {
            "type": "multiple",
            "difficulty": "easy",
            "category": "Science: Computers",
            "question": "Which SQL keyword is used to fetch data from a database?",
            "correct_answer": "SELECT",
            "incorrect_answers": ["INDEX", "VALUES", "EXEC"],
        },
        {
            "type": "multiple",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "In the programming language &quot;Python&quot;, which of these statements would display the string &quot;Hello World&quot; correctly?",
            "correct_answer": "print(&quot;Hello World&quot;)",
            "incorrect_answers": [
                "console.log(&quot;Hello World&quot;)",
                "echo &quot;Hello World&quot;",
                "printf(&quot;Hello World&quot;)",
            ],
        },
        {
            "type": "multiple",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "Moore&#039;s law originally stated that the number of transistors on a microprocessor chip would double every...",
            "correct_answer": "Year",
            "incorrect_answers": ["Four Years", "Two Years", "Eight Years"],
        },
        {
            "type": "multiple",
            "difficulty": "medium",
            "category": "Science: Computers",
            "question": "Which one of these is not an official development name for a Ubuntu release?",
            "correct_answer": "Mystic Mansion",
            "incorrect_answers": ["Trusty Tahr", "Utopic Unicorn", "Wily Werewolf"],
        }
]
